/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import java.time.LocalDate;

public class PessoaTest {

    @Test public void validarLancamentos(){
        int[] primeiroLancamento = {10,20,30,40,50};
        int[] segundoLancamento = {10,20,30,40,50};

        assertArrayEquals(primeiroLancamento, segundoLancamento);
    }

    @Test public void validarSEObjetoEstaNulo(){
        Pessoa  pessoa = null;
    
        assertNull(pessoa);

        pessoa = new Pessoa("Teste", LocalDate.now());
        assertNotNull(pessoa);

    }

    @Test public void validarCalculoDeIdade() {
        Pessoa cryslei = new Pessoa("Cryslei", LocalDate.of(1998, 3, 29));
        assertEquals(26, cryslei.getIdade());
    }

    @Test public void verificaSeEhMaiorDeIdade() {
        Pessoa cryslei = new Pessoa("Cryslei", LocalDate.of(1998, 3, 29));
        assertEquals(26, cryslei.getIdade());
        assertTrue(cryslei.ehMaiorDeIdade());
    }
}
